apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-api
  template:
    metadata:
      labels:
        app: fastapi-api
    # spec: #uncomment this if u use k8s
    #   containers:
    #   - name: fastapi-api
    #     image: your-dockerhub-username/fastapi-dev:latest
    #     ports:
    #     - containerPort: 80
    #     resources:
    #       requests:
    #         cpu: "250m"
    #         memory: "256Mi"
    #       limits:
    #         cpu: "500m"
    #         memory: "512Mi"