name: format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [ruff, mypy]
        include:
          - linter: ruff
            command: ruff check --diff .
          - linter: mypy
            command: mypy .
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # Pastikan versi Python sesuai
      - name: Install dependencies
        run: |
          pip install uv
          uv sync --frozen
      - name: Run ${{ matrix.linter }} check
        run: ${{ matrix.command }}